### ISSUE TITLE
Nova URDF

### ISSUE THREAD

**Issue by RPKrijnen** [Adjuvo/senseglove_ros_ws#11]
feature that should implement xacro/urdf files for the NOVA gloves. Definition of done would be to be able to visualize the urdf in RVIZ.

**Comment by iamjoong9** [comment]
I wonder if URDFs and CAD model of the Nova gloves are available. I cannot find any in this repository.

**Comment by RPKrijnen** [comment]
@JoongKu-Lee These are indeed not available. Back in July we were toying around with the idea to add URDFs for the Nova gloves, but we opted out due to low demand. The active maintainer of this workspace is @akshayrmenon at the moment. Maybe he can help you more.

**Comment by akshayrmenon** [comment]
@JoongKu-Lee We have your support ticket regarding ROS compatibility of NOVA. I believe the support team will send my answers to you by mail today. However, I shall provide my answer here as well.

"It is scheduled to have a release for ROS-Noetic with our new C++ back end integration next month. After the new release, it is yet to be decided whether we would be providing NOVA with ROS Compatibility or not. It is a management decision, based on demand. You can expect an update regarding this, next month.

However, for one of our Tele-Robotics project, we used a ROS-Bridge-WebSocket to communicate with Unity. ROS would be the server, a Unity Project will be the client. You can, therefore use the SenseGlove's Unity plugin to use the NOVA, import Siemen's ROS# Asset to connect to the server, publish and subscribe to topics, set/get ROS parameters."

**Comment by iamjoong9** [comment]
Thank you for your fast response! @Deakensbubbles @akshayrmenon

Can you confirm if my understanding is correct? 
1. it is currently not possible to run senseglove nova with senseglove_ros_ws repository.
2. noetic package to run senseglove nova will be released next month. 
3. you can run nova with the noetic package that will be released next month, but we don't know what will happen after that. 
4. you can use ROS-bridge-websocket to run nova on Ros. 

**Additionally, I want to get the CAD model of the Nova because I need to design some mount. where should I request it?

**Comment by akshayrmenon** [comment]
Hi @JoongKu-Lee ,

**(1)** Yes, it is not possible to run SG-NOVA with the current senseglove_ros_ws repository.
**(2)(3)**  No. Official Nova Support for ROS was not considered because we were never able to connect to one on Linux before. Recently, NOVA became compatible with Linux. So firstly, we need to update the C++ libraries to v2.0, and release it for ROS-Melodic and ROS-Noetic. This is scheduled as part of our software releases, next month.

However, it will run only on DK units, and not with SG-NOVAs. Internal talks have been going on to give ROS Support for NOVA. It is yet to be scheduled. Kindly wait until next month regarding the NOVA-ROS update.

**(4)** You can use the Unity Plugin of Senseglove (in Unity), import ROS# asset, start a rosbridge-websocket, and communicate to your robot in ROS with this websocket. If you would like support on this architecture, we can have a call.

**Additionally** Yes, we have seen your support ticket. If management approves sending the CAD models, you will receive a mail soon. Your request is currently at the management side, kindly wait for their reply.

**Comment by iamjoong9** [comment]
Thanks @akshayrmenon !

Looking forward to check new software release next month! and I would like to have a ROS support for NOVA, too :)

I'll also wait for the CAD models. 

Thank you and hope you have a nice day.
